name: "ex_06_laz"
version: "1.0"
config-version: 2

profile: clickhouse_ftw
model-paths: ["models"]
macro-paths: ["macros"]  

models:
  ex_06_laz:
    clean:
      +schema: clean
      +materialized: table
    mart:
      +schema: mart
      +materialized: view
