{{ config(materialized="table", schema="mart", alias="g2_top_revenue_by_genre_per_country_shi", tags=["mart","chinook","analytics"]) }}

-- Top Revenue by Genre per Country analysis for Grp2
-- This query calculates the total revenue generated by each genre in each country
-- using actual invoice data from the Chinook database (Grp2 tables)
WITH revenue_by_genre_country AS (
    SELECT 
        c.country,
        g.name as genre_name,
        SUM(il.unit_price * il.quantity) as total_revenue,
        COUNT(DISTINCT i.customer_id) as unique_customers,
        COUNT(il.invoice_line_id) as total_tracks_sold,
        SUM(il.quantity) as total_quantity
    FROM {{ source('raw', 'chinook___invoice_line_shi') }} il
    JOIN {{ source('raw', 'chinook___invoice_shi') }} i 
        ON il.invoice_id = i.invoice_id
    JOIN {{ source('raw', 'chinook___customer_shi') }} c 
        ON i.customer_id = c.customer_id
    JOIN {{ source('raw', 'chinook___track_shi') }} t 
        ON il.track_id = t.track_id
    JOIN {{ source('raw', 'chinook___genre_shi') }} g 
        ON t.genre_id = g.genre_id
    GROUP BY 
        c.country, 
        g.name
),
ranked_genres AS (
    SELECT 
        country,
        genre_name,
        total_revenue,
        unique_customers,
        total_tracks_sold,
        total_quantity,
        ROW_NUMBER() OVER (PARTITION BY country ORDER BY total_revenue DESC) as genre_rank
    FROM revenue_by_genre_country
)
SELECT 
    country,
    genre_name,
    ROUND(total_revenue, 2) as total_revenue,
    unique_customers,
    total_tracks_sold,
    total_quantity,
    genre_rank
FROM ranked_genres
WHERE genre_rank <= 5  -- Top 5 genres per country
ORDER BY 
    country ASC,
    total_revenue DESC